import logging
import logging.handlers
import gym
from gym.envs.classic_control import rendering
import roslibpy
import roslibpy.actionlib
from gym.utils import seeding
from .gazebo_connection import GazeboConnection
from .controllers_connection import ControllersConnection


class RobotGazeboEnv(gym.Env):

    def __init__(self,logger:logging.Logger,
                robot_name_space,controllers_list,reset_controls = False,
                
                reset_world_or_sim="SIMULATION RESET", host = 'localhost', port=9090
                ):

        super().__init__()
        self.logger = logger
        self.client = roslibpy.Ros(host=host, port=port)
        self.client.run()
        # To reset Simulations
        self.logger.debug("START init RobotGazeboEnv")
        self.gazebo = GazeboConnection(self.client,reset_world_or_sim,logger=logger)
        self.controllers_object = ControllersConnection(self.client,logger,namespace=robot_name_space, controllers_list=controllers_list)
        self.reset_controls = reset_controls
        self.seed()

        # Set up ROS related variables
        self.episode_num = 0
        self.cumulated_episode_reward = 0


        

        # We Unpause the simulation and reset the controllers if needed

        self.gazebo.unpauseSim()
        if self.reset_controls:
            self.controllers_object.reset_controllers()

        self.logger.debug("END init RobotGazeboEnv")

    # Env methods
    def seed(self, seed=None):
        self.np_random, seed = seeding.np_random(seed)
        return [seed]

    def step(self, action):
        """
        Function executed each time step.
        Here we get the action execute it in a time step and retrieve the
        observations generated by that action.
        :param action:
        :return: obs, reward, done, info
        """

        """
        Here we should convert the action num to movement action, execute the action in the
        simulation and get the observations result of performing that action.
        """
        self.logger.debug("START STEP OpenAIROS")

        self.gazebo.unpauseSim()
        self._set_action(action)
        self.gazebo.pauseSim()
        obs = self._get_obs()
        done = self._is_done(obs)
        info = {}
        reward = self._compute_reward(obs, done)
        self.cumulated_episode_reward += reward

        self.logger.debug("END STEP OpenAIROS")

        return obs, reward, done, info

    def reset(self):
        self.logger.debug("Reseting RobotGazeboEnvironment")
        self._reset_sim()
        self._init_env_variables()
        self._update_episode()
        obs = self._get_obs()
        self.logger.debug("END Reseting RobotGazeboEnvironment")
        return obs

    def close(self):
        """
        Function executed when closing the environment.
        Use it for closing GUIS and other systems that need closing.
        :return:
        """
        self.logger.debug("Closing RobotGazeboEnvironment")
        self.client.terminate()

    # def render(self, mode='human',close=False):
    #     raise NotImplementedError()

    def _update_episode(self):
        """
        Publishes the cumulated reward of the episode and
        increases the episode number by one.
        :return:
        """
        self.logger.debug("REWARD ==>"+str(self.cumulated_episode_reward)+",EP="+str(self.episode_num))

        self.episode_num += 1
        self.cumulated_episode_reward = 0

    # Extension methods
    # ----------------------------

    def _reset_sim(self):
        """Resets a simulation
        """
        self.logger.debug("RESET SIM START")
        if self.reset_controls :
            self.logger.debug("RESET CONTROLLERS")
            self.gazebo.unpauseSim()
            self.controllers_object.reset_controllers()
            self._set_init_pose()
            self.gazebo.pauseSim()
            self.gazebo.resetSim()
            self._set_model_pose()
            self.gazebo.unpauseSim()

        else:
            self.logger.debug("DONT RESET CONTROLLERS")
            self.gazebo.unpauseSim()
            self._set_init_pose()
            self.gazebo.pauseSim()
            self.gazebo.resetSim()
            self._set_model_pose()

        self.logger.debug("RESET SIM END")
        return True

    def _set_init_pose(self):
        """Sets the Robot in its init pose
        """
        raise NotImplementedError()
    
    def _set_model_pose(self):
        """Sets environment object in specific pose
        """
        raise NotImplementedError()

    def _check_all_systems_ready(self):
        """
        Checks that all the sensors, publishers and other simulation systems are
        operational.
        """
        raise NotImplementedError()

    def _get_obs(self):
        """Returns the observation.
        """
        raise NotImplementedError()

    def _init_env_variables(self):
        """Inits variables needed to be initialised each time we reset at the start
        of an episode.
        """
        raise NotImplementedError()

    def _set_action(self, action):
        """Applies the given action to the simulation.
        """
        raise NotImplementedError()

    def _is_done(self, observations):
        """Indicates whether or not the episode is done ( the robot has fallen for example).
        """
        raise NotImplementedError()

    def _compute_reward(self, observations, done):
        """Calculates the reward to give based on the observations given.
        """
        raise NotImplementedError()

    def _env_setup(self, initial_qpos):
        """Initial configuration of the environment. Can be used to configure initial state
        and extract information from the simulation.
        """
        raise NotImplementedError()